### ISSUE TITLE
1901010000 -MIT-自学 MIT 原版书 第三章

### ISSUE THREAD

**Issue by clairetyx** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#1]
### 学员信息
- 学号：1901010000
- 学习内容：自学 MIT 原版书 第三章一些简单的数值程序/其他补充阅读材料
- 学习用时：60min

### 学习笔记

1. 完成30天打卡后，首次来完成当周打卡任务。发现Python健脑最好别间隔太久，要不一回来看就又觉得有丢丢陌生 
2. 这章其实就还是在继续复习while循环和for循环的基本编写方式。喜欢书里的写法，每次讲解完程序就会写"有经验的程序员一般是这样做的"。里面有一个例子是程序会永远运行下去，因为循环体没有减少两个参数之前的差距。经验丰富的程序员经常会插入一些print语句，比如测试递减函数是否真的递减。
3. 这也是优秀教练的教法，比如今天我看到蔡教练给姜翔发的google工程师的编写规范·。下面也也发给大家一起参考。
4. 看到特别好玩的三个语录分享给大家一乐：

这个"电话"有太多缺点，没法当作真正的通信手段。这东西本身对我们没有价值。

——西联公司1976年内部备忘录

我看全世界对计算机的需求量总共可能只有五台。

——托马斯沃森，IBM董事长，1943年

没有任何理由能够证明，人人都想在家里拥有一台计算机。

——肯奥尔森，DEC公司总裁和创始人，1977年

**Comment by realcaiying** [comment]
已收录。
