### ISSUE TITLE
1901050081-自我介绍

### ISSUE THREAD

**Issue by QueenieQ2019** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#10]
### 基本信息
姓名：QQ
学号：1901050081

### 工作背景
无特定行业

### 自我介绍
我是一名 80 后大龄待业女青年，学习编程是为了更快的适应巨变的社会，获得一个长期奋斗的方向。再选择数据分析作为进阶学习，以求先掌握一门技术作为谋生手段，并学会如何透过现象看清本质，在数据中获得最有价值的信息，不被表象迷惑，做出最有利于自我的长远决策。期望可以通过不断打磨自己的技艺，靠自己的双手过上自己喜欢的生活，由自己掌握的时间和节奏，不再活在别人设定的框架中。

**Comment by realcaiying** [comment]
已收录。
