### ISSUE TITLE
1901100209-自学训练营学习18群-DAY2

### ISSUE THREAD

**Issue by huangmengzhu** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#171]
### 学员信息
- 学号：<1901100209>
- 学习内容：<helloworld编码>
- 学习用时：<3h>

### 学习笔记
1、在网上搜索如何使用vscode和helloworld编码的编写，直接搜索“使用python写helloworld”，网上信息太多，但是无法知道怎么开始使用vscode开始写编码
<收获总结>
在网上很容易可以直接查到helloworld的程序，如何激活配置python的环境。但是不知道如何使用vscode开始写编码，可能是我的搜索能力差，一直没找到如何开始编码，后面我转为查看vscode的软件信息，摸索着知道了要先在本地建立文件夹再从vscode中打开。
<遇到的难点与问题（是否解决）>
1、不知道如何在vscode中开始编程，找不到对应的界面。解决方法：通过网上的信息及自己对vscode的摸索，并通过猜想进行尝试，找到了方法，即先在本地建立文件夹再在vscode中打开。
2、提交作文没有在本地仓库selfteaching-python-camp中新建文件夹，导致作业无法提交，第二次操作时忘记了第一次操作的步骤。这也是没有根本了解selfteaching-python-camp的作用和原理所导致

**Comment by XINGRUFANG** [comment]
link #99
