### ISSUE TITLE
1901100163-自学训练营学习18群-DAY4学习笔记

### ISSUE THREAD

**Issue by Eric-luo2019** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#189]
### 学员信息
- 学号：1901100163
- 学习内容：1. 使⽤ for...in 循环打印九九乘法表  2.使⽤ while 循环打印九九乘法表并⽤条件判断把偶数⾏去除掉
- 学习用时：<10小时>

### 学习笔记

<收获总结>开始对PYTHON的机构和用语、命令有感觉，对一些语法也慢慢地熟悉。对于
for..in 和while 的运用，里面的逻辑关系还是搞得不清晰。
<遇到的难点与问题（是否解决）>
1，for...in 和 while 的逻辑关系还是模糊
2，对于命令的缩进，掌握的不清晰，也是逻辑的问题没搞清楚

**Comment by Eric-luo2019** [comment]
@XINGRUFANG

**Comment by XINGRUFANG** [comment]
已合并到 #178
