### ISSUE TITLE
<1901100209>-<自学训练营学习18群>-<计算器>

### ISSUE THREAD

**Issue by huangmengzhu** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#192]
### 学员信息
- 学号：<1901100209>
- 学习内容：<简单的计算器编程>
- 学习用时：<3h>

### 学习笔记
学习到了各种函数、字符串、类等定义，有些不是很了解，看的不是很懂，只能后面深入了解或者在使用中去学习
<收获总结>
1、学会了如何定义一个函数
2、学习了如何使用if函数
<遇到的难点与问题（是否解决）>
1、在编程时，知道如何定义加减乘除的函数，但是不知道如何输入参数，看了两遍的资料还是不清楚，后来自己上网查找别人是怎么写的，才知道了要使用if函数。

**Comment by XINGRUFANG** [comment]
link #99
