### ISSUE TITLE
1901100246］自学训练营010期连续班 第9课学习笔记打卡

### ISSUE THREAD

**Issue by chenchun87** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#250]
### 学员信息
- 学号：<1901100246>
- 学习内容：<第9课>
- 学习用时：<2小时>

### 学习笔记

<收获总结>
完成第9课学习。

<遇到的难点与问题）>
有一个疑问：在桌面上的代码仓库中，有tang300.json这个文件，将它pull request到网络仓库后，没有看到这个文件。

**Comment by XINGRUFANG** [comment]
link #249
