### ISSUE TITLE
1901090045-自学训练营学习10群-DAY3学习总结

### ISSUE THREAD

**Issue by qinshoubg** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#273]
### 学员信息
- 学号：1901090045
- 学习内容：编写计算器
- 学习用时：5h

编写计算器的作业是完完全全抄了别的同学的，很惭愧，但是我确实不会，确实一点思路都没有，甚至怀疑这些作业是给零基础的人准备的，我DAY2才学会print("hello world")，DAY3就要写一个这样的东西
![image](https://user-images.githubusercontent.com/54206237/63595567-d69b5000-c5eb-11e9-97be-19222c7d9e89.png)
看了官方文档，很认真看了，但是一到作业的时候就是一脸懵逼，给人的感觉就像是从A-Z学完26个字母然后就让你去写文章一样，我觉得只有50%的人坚持下来不是没有原因的。
不好意思，我是初学者真正的初学者，在这就是我最真实的感受

<收获总结>

<遇到的难点与问题（是否解决）>

**Comment by XINGRUFANG** [comment]
link #246

**Comment by XINGRUFANG** [comment]
加油加油，万事开头难，自学更不容易，但是自学真的是每个人都需要的，坚持，加油
