### ISSUE TITLE
1901050081 - 数据分析营学前作业

### ISSUE THREAD

**Issue by QueenieQ2019** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#29]
### 基本信息
姓名：QQ
学号：1901050081

### 工作背景
待业（无特定行业）

### 自我介绍
作为一名 80 后待业大龄女青年，学习编程是为了使自己更快的适应巨变的社会，获得一个长期奋斗的方向。再选择数据分析作为进阶学习，以求先掌握一门技术作为谋生手段，并学会如何透过现象看清本质，在数据中获得最有价值的信息，不被表象迷惑，做出最有利于自我的长远决策。期望可以通过不断打磨自己的技艺，靠自己的双手过上自己喜欢的生活，由自己掌握的时间和节奏，不再活在别人设定的框架中。

目前学习阶段和学习困惑：现阶段已经完成了入门训练营和 MIT 视频公开课的学习，还在继续了解 Python 的语言特性。不知道初高中数学都丢光了，数据分析能学得好吗？是不是先学会爬虫，再学习数据分析师会好一些？还是直接挑战数据分析师呢？要系统的学习，还需要学习哪些课程会更好呢？

**Comment by realcaiying** [comment]
已收录。
