### ISSUE TITLE
1901050035 自学数据训练营 

### ISSUE THREAD

**Issue by gd139** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#30]
### 基本信息
姓名：<老罗>
学号：<1901050035>

### 工作背景
<网络维护和管理>

### 自我介绍
【自我介绍】我是老罗，在广州工作，日常负责网络运行和维护管理工作。工作的老兵，编程的新手，很高兴有机会和大家一起参加数据营学习数据分析和处理，提高工作的效率和自我价值。
【为什么想学习数据分析，希望学完之后应⽤在什么场景】
工作20多年，大部分时间以通过系统出告警或用户投诉等传统的方式，来处理网络出现的故障或隐患，工作非常被动；而且随着网络的快速大规模的扩容，现有的人手和手段非常缺乏和落后，希望通过计算机自动收集日志和性能统计数据，分析和评估当前网络运行的状态，以实现对网络运行中的故障自动快速的定位和容量主动精准扩容。
 
【当前的学习阶段和疑惑】：前期参加了自学训练营，初步掌握了Python的程序的运行和基本函数规则等，后续希望通过本期数据营，学会和掌握一套数据分析和处理工具，支撑日常工作，实现对网络系统运行的自动采集、统计和分析，提高管理效率。

**Comment by realcaiying** [comment]
已收录。

**Comment by realcaiying** [comment]
2924c9d8cb443b03e30a4ecee1541c8487c13bb0
