### ISSUE TITLE
1901010061_数据分析营学前作业

### ISSUE THREAD

**Issue by musicmiao** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#33]
基本信息
姓名：Music
学号：1901010061

工作背景
会计

自我介绍
我是一名90后南方人，从事玩具行业.
为什么想学习数据分析：我对数据分析是没有接触过的，从自已的理解角度，数据分析的作用应该是收集数据信息，然后信息分析，帮助自已作出一些决策判断。我们是处在信息发达的环境，如何取得高质量的信息并学会分析学习。学习数据分析是利大于弊的。
学后应用场景： 生活与工作中能使用数据分析来优化决策。
学习阶段和疑惑：在几个月前参加了训练营，通过自学，初步认识了python。
学完之后，感觉还是有些懵，感觉学完容易忘，不会灵活使用。之后进入到MIT的学习，
重新思考了学习这件事情（为什么我学习后的知识容易忘，我应该怎么做，有什么学习方法是适合我的），通过看学习相关的书箱、网上找资料，找到了合适自已学习的方法，目前正在适应中。

**Comment by realcaiying** [comment]
已收录。
