### ISSUE TITLE
gouliqiao_数据分析营学前作业

### ISSUE THREAD

**Issue by gouliqiao** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#34]
姓名:
  苟利桥，当然也有叫大桥的，叫小桥的，等等。
  
工作背景:
  目前从事IT工程与运维项目的实施工作，主要是服务器存储以及华为云计算的实施交付于维护相关工作。
  
自我介绍:
  虽然岁数不大，30都还差点，但是一路走来一直在学习，从中受益匪浅，我以前大学毕业后是搞基础网络维护与个人pc电脑维保工作的，到后来的企业网维护，企业网IT维护，再到现在的企业网、运营商IT云计算维护。由于我本人背景并不好，所以从技术中获益的幅度更是十分的可观，总是有几句话一直觉得特别受用:
  凡事有失有得有得有失，有些事情别人不愿意做的、累的、看不起的可能里面会有机会。
  君子性非异也，善假于物也。下面再详述。
  
为什么想学习数据分析，希望学完之后应⽤在什么场景：
  这里接着说刚才那句话，像我们很多一线的工程师是骨子里是不乐意搞技术这个东西的，理由很简单就是不受用，性价比很低，毕竟学习技术研究技术非常的花精力，而实际的效益确并不好，这点我自己是深有体会，所以好多一线工程师实际上干的是业务的活，就是变相的搞销售拿提成，真有解决不了的问题，有二线，有研发支持，压根不需要自己花精力去研究。
  
  交代一下背景，更加方便于自己阐述学习的动力和心态。本人一直在工程师岗位那么多年，深刻的认识到技术的重要性，概况起来就两个字效率。同样是做一个事情，我懂技术，我多会那么一些工具，在故障诊断上，工程交付上，思维逻辑上，完全能成指数级的方式改善自己的工作方式，大大提升效率，节约出更多时间来进一步加深扩充技术，从而实现良性循环，量变到达质变，接着而来的就是生活的改变。
  
  话又说回来了，为什么要学习数据分析，是完全因为工作么？显然不是，显然我们工作对数据分析的依赖并不大。如上文讲到，技术改变了我分析问题，看待问题事务的逻辑，提供了我终身学习进步的可能，进而深刻的认识到当下时代从数据中获利的趋势必然会大于我通过工作时间来获利的可能。
  
  好了，上文讲到我们想通过数据来获利，诶就是挣钱，不以挣钱为目的的学习技术那都是耍流氓。
  
  那么我们学完后要干点什么呢：
  当然学习数据分析只是我要干的事情中的一部分，就目前我最终想干的事情是通过爬虫、数据分析、信息论、离散数学等，建立一个股票等二级市场涨跌的交易模型，极大概率从中实现获利。
  同时，还想通过数据分析，爬取与分析当下的电商平台，比如美团，淘宝，大众点评，链家等等平台的优惠信息以及其他商业价值信息，帮助实现获利决策模型。
  最终目的就是从当前的通过完完全全的工作时间获利的模型中解脱出来，创造更多的可能，实现财务自由。
  
目前自己的学习阶段和疑惑
  当然想干那么多事情，单纯只靠数据分析是远远不够的。所以还是要关注当下，沉下心来，一步一个脚印的前进，虽然看过很多书，懂得很多道理，但是我每天依然还是在做调系统、写代码。
  
  因此当下依然还是处在通过代码来调优工作效率的阶段。不过已经能通过爬虫获取到海量数据，存储数据了，所以完全可以进一步进阶来分析这些数据，展现这些价值数据的时候了。
  
  既然如此，那大家就一起共同加油，共渡剩下的阶段吧。
Fighting

**Comment by realcaiying** [comment]
已收录。 学号 1902100002
