### ISSUE TITLE
1902100001-自学数据营-自我介绍(学前作业)

### ISSUE THREAD

**Issue by M-O-Node** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#39]
### 基本信息
姓名：王学闻 , 大家可以叫我学闻
学号：1902100001

### 工作背景
目前从事Java程序员工作(三年工作经验)

### 自我介绍
我是一名在职的Java程序员 , 在这几年的工作中除了敲代码 , 看的最多的就应该是很多所谓的产品经理根据自己的并不实际的调查确定用户的需求 , 然后进行项目开发 , 结果开发的产品犹如石沉大海 , 然后......就没有然后了 . 

作为一个底层业务的实现者 , 我深知这种现象在软件开发的普遍性 , 也知道在那些所谓的产品经理眼中用户 "应该" 有的需求是不对的 , 明白这些又怎样 ? 如果换我去做同样的工作 , 或许也会犯一样的难 . 也会一样淹没在无边无际的不确定性之中 . 

我想这样的焦虑并不只有我一个人感受得到 . 

然而大数据却能解决这样的问题 . 我们可以运用大数据思维去消除不确定性 , 利用它实现精准服务 , 它还能帮我们动态的调整做事策略 , 还能用它去发现未知规律 , 等等等等 . 能够做到让我们的分析更加贴近现实 , 我想大数据思维应该成为每一个有志于在未来数据大潮中过好日子的人的必修课 .

目前的学习阶段 , 初级

**Comment by realcaiying** [comment]
已收录。
