### ISSUE TITLE
1901010014-数据营-自我介绍

### ISSUE THREAD

**Issue by WengYadong** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#45]
### 基本信息
姓名：白头翁
学号：1901010014

### 工作背景
销售类

### 自我介绍
大家可以叫我白头翁，从事销售类工作。

参见Python 训练营进阶课程，是因为想换个行业工作，因为的的确确这是个变化频率与幅度都在不断加大的时代，10年前我还不知道二维码是什么，但今天二维码已经成为了移动互联网的入口，现在出门带个手机就可以搞定许多生活事项，且2009到2019这10年技术发展非常快，移动互联网、云计算、大数据、人工智能、区块链…… 都在一步步影响着各行各业，与其将来被技术革命，不如现在趁年轻，相对有充裕时间和充足精力，去拥抱变化。

目前我在反复看《自学是门手艺》这本书，能看懂一些 Python 程序，但自己实际动手写个小程序还是很困难。

愿我们自学 Python 进阶训练营的同学们一起讨论问题，共同进步，用三个月时间让自己学有所获，用一年时间把自学这门手艺和数据分析能力磨练的很好，足够应对日常工作生活所需。一起加油！

**Comment by realcaiying** [comment]
已收录。
