### ISSUE TITLE
1901010056-自我介绍

### ISSUE THREAD

**Issue by pony6666** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#5]
### 基本信息
姓名：马林
学号：1901010056

### 工作背景
大学狗

### 自我介绍

我叫马林，一名普通二本农学专业的学生，对于 Python 的学习是零基础，学习Python的理由是树联寻英发布的《大数据人才报告》中的一项数据：目前我国大数据人才仅46万，在未来 3~5 年内大数据人才缺口达 15000000之巨。

我学习Python的目的目前是为了将来的工作加筹码，“独善其身”完了以后，希望可以“平天下”，哈哈说得有点大了，目前希望用途：

- 可以用在对Python领域工作岗位的分析上
- 对自己的两本时间记录数据的分析上
- 等等

**Comment by realcaiying** [comment]
已收录。

https://github.com/selfteaching-learning-notes/selfteaching-learning-notes.github.io/commit/d27622a9a5478422d46c66b52b804579b65bcaae
