### ISSUE TITLE
1901010056-自学训练营学习1群-Python 14 天入门

### ISSUE THREAD

**Issue by pony6666** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#7]
### 学员信息
- 学号：1901010056 ——马林同学
- 学习内容：Python 14 天入门
- 学习用时：总用时110.2小时

#### day1

学习时长:7个小时

学习内容

1. 创建了两个自己的代码仓库，学会使用branch 和pull requst
2. 在Github的仓库提交issue
3. 通过Github Desktop 将ma-hellow-world 仓库克隆到了本地电脑
4. 将公共作业的仓库克隆到了本地电脑，在本地仓库的exercises目录下藏剑文件
5. 通过Github桌面客户端将本第电脑的变更推送到自己的账户下的作业仓库
6. 向远程作业仓库的master分支发起了pull request

收获

1. pull request are zhe heart of the collaboration shows diffs or differences of the content from both branch
2. make adn commit changes 和open a pull request for changes to the develop和merge your pull request 在三个步骤在初期的时候搞不明白
3. 认识了不少单词和句子
4. 在找按钮的过程中，经常忽略下拉找找
5. 对于一些难词很多的生词，可以直接字典翻译，提高效率

#### day2

学习时长:7个小时

收获

1. 锻炼自己，通过找、 问的方式去解决问题。
2. 顺利下载并安装了Anaconda，并在其界面安装了VScode，Jupyter Notebook 和 JupyterLab. 
3. 在 vscode 中配置 Python 环境选择特定环境，应该输入“Python: Select Interpreter”进行选择。但一直没有对应的选项。通过糖总发总的issue链接找到答案。要搜索“language"——“Configure Display Language”——将"locale":"en"修改为"locale":"en-US"，保存。重启。
4. 用jupiter note book 阅读笑来老师新书，被网页上的一个烟雾弹，所困住。经过助教点播，才解决，发现也不是大问题。

#### day3

学习时长:4个小时

收获

1. 在自己的编码器上跑出程序
2. 由于认真看过笑来老师的新书，再结合google翻译，看起来英文文档还比较顺畅，但是一下子也没好好吸收

感悟

1. 实际的操作代码很多都是可以从网上找到的。这对于初步阶段的我很有利用价值。
2. 用好google和google 翻译，似乎没有什么事是解决不了的

#### day4

学习时长:6个小时

遇到问题

1. 当拿到题时，没有任何头绪。知道会用到条件判断和循环语句，但是不知道怎么用。最后在issue上解决了问题
2. 在写代码时忘了加冒号，导致运行失败
3. 在写while语句时，发现空格也非常重要，否则，程序是没办法成功的

感悟

1. 细心也非常重要
2. 把学的内容解释，可以在代码中加井号，解释出来，加深理解

#### day5

学习时长:9.5个小时

学习内容

1. 字符串的基本处理，将文本里的单词进行替换，剔除不想要的单词，翻转单词中的大小写字母
2. 用字典统计字符串样本中英文单词出现的次数，按照出现次数从大到小进行排列，注意排除符号
3. 将数组顺序进行翻转，用字符符串切片方式取出第三到第八个字符，将获得的字符进行翻转，将结果转化成整型，分别转化成二进制，八进制，十六进制
4. 学习笑来老师书上的内容，知道了笑来老师书的代码是可以直接在lab上直接运行的操作，并且可以改着玩
5. 将单词中包含ea的单词除去的时候，一开始参考用del但是后面的怎么跑都不成功。后来又参考另外几名同学的作业，和issue，才知道del 的用途一般用来删除数组中的一个元素，或者删除一个变量

感悟

1. day5的实用性很强，有四六级或者考研的所有的卷子text,就可以对里面所有的单词出现的频率进行统计，从而把时间都花在记忆高频率不会的单词上，只是最后转化成二进制，八进制，十六进制，暂时还不知道有什么用
2. 在打代码的时候，需要注意冒号是否打了
3. 可以把笑来老师的书提上日程上来，对于增加对python有很大帮助，上面的代码可以直接修改，对于无论是函数，数据类型，还是其中的逻辑关系的理解都又很大的帮助
4. 程序跑错误后的提示，也至关重要，提示里的单词一定要明白意思
5. 似乎是上点门道了。结合笑来老师的书，提供了很多的方便

#### day6

学习时长:5个小时

学习内容

1. 封装统计英文单词词频的函数。这个任务是基于昨天 的内容
2. 封装统计中文汉字字频的函数，判断是不是汉字这个问题需要一定的时间

感悟

1. 虽然作业时做下来了，但是作业里面还是有很多东西一知半解，无论是函数的运用，还是字符的形式，等等一系列内容都是需要加强训练的，都是需要时间和精力的投入才能慢慢上手的
2. 已经完成的同学的作业也是有好有坏，有的非常的简洁，有的非常的繁琐，再参考的时候一定要多看几个，比较一下
3. day5的Python中的禅宗中的这句话”面对困惑，拒绝猜测的诱惑”给自己提了个醒，不要懒的查找就去猜测函数的功能或者不会的内容

#### day7

学习时长:10.5个小时 感悟

1. 冥想对于编程来说有很大的帮助，因为无论是调试一个程序，还是阅读一段自己理解的概念，都能够让自己很清楚很客观认识自己的现状，自己的处境，自己正在挣扎在一个怎样的问题上。缺乏元认知能力的话，很容易陷入低级的困惑当中，甚至即使过了很长时间自己的对问题的思考都得不到推进。
2. 做题的时候，可以把笔记本就打开，遇到不会的问题，就敲到上面，遇到自己不熟悉的知识点就敲到上面。因为不会的都是需要自己加强的，所以敲一遍一点都不过分，甚至多敲几遍都不过分
3. 在把笑来老师的part1再看一遍，发现这一部分需要多看几遍，不然不容易掌握，多看一遍对全局都有一个更深刻的理解
4. 把对英文的词频和中文的字频包装成一个函数，需要的时候随时调用，这样真的剩了不少事

知识点总结

1. 循环语句可能带有一个else子句；这个else子句它会在循环遍历完列表的时候被执行（另一种情况暂时没遇到先不讨论），但是不会在循环被break语句终止时被执行。 break 它也属于一个子句中的一个条件，表示跳出最近的for循环，（while没遇到暂时不讨论），控制流程往下跑。但是一种情况比较特殊就是往下跑的时候遇到else语句，此时else语句不被执行
2. 琢磨流程控制中的break和continue需要时间多点。continue语句看官方文档稍微好理解，就是当条件被满足时，也就是continue被执行时，流程被控制往上跑，继续上面的循环

易错点

1. 在mydouble文件夹的同级目录下，创建main.py文件。意思就文件夹mydouble和文件main.py都出现在同一个页面中，容易犯的误区就是，看到，一个文件夹，一个文件，想当然地认为这个文件就在文件夹里。

#### day8

学习时长:3.7个小时

学习收获

1. Ctrl +Backspace是删除整个单词
2. Ctrl+左右移动键是光标来回在整个单词间跳动
3. Tab +右移动键  可以自动补全函数和前面已经输入过的字符

感悟

1. 尝试一下，通过写的方式将自己的思想过程具体化，避免失去重点，让任务得不到推进。
2. 一切提升效率的东西都要尽快第掌握

#### day9

学习时长:11.5个小时

卡点

1. 不知道怎么把VS code给玩坏了，以前的所有作业的程序都运行不了，但是发现前已经花了好多时间在上面这是第一个卡点，卡了我不少时间，最后在折腾不行，听教练的建议又重新安装了一遍，随后才正常运转
2. 关于tang300.json路径的设置，我一直担忧是自己的运行系统是C盘，但是作业在D盘的原因，在参考前辈的作业，什么情况都有，况且每个人的路径都不一样，苦苦挣扎，也卡了不少时间，最后在YouTube上的相关视频找到启发，让程序给运行成功了
3. 在找问题的时候，由把本地文件的仓库的文件位置给变动了，所以就是在desktop上费了点时间

感悟

1. 累坏了，不过在通过自己的努力查找，让程序运行成功的一瞬间，感觉自己的真牛，差点都认怂了，幸好没放弃，充足的时间预算也相当重要，   

#### day 10 

学习时长:11个小时

1. 下载完jieba不知道怎样安装，在issue上虽然有个方法，但是在终端输入指令根本不会，在教练逯彬杨的帮助下，又查阅相关的资料解决
2. 程序死活运行不了，以前的做的有的也运行不了，教练协助，修改了部分代码，还是不行，尝试了，各种办法以后（有一个尝试把操作页面改成中文了），为下一步发现问题铺一步路，尝试到11点，和辅导员老白的聊天中，他提了一句，配置问题，然后第二天发现有一个bug确实是配置问题，以前做的能运行了
3. 找不到路径问题，由于前段时间，一不小心玩坏了本地，删除了以后，导致路径发现问题，后来又把程序中的路径改了过来
4. 程序运行找不到mydoule中的stats_world，最后索性都在后面加了一个数字，最后终于成功

感悟

1. 做的时候，不知道是以前的坑，还是现在的坑在等着你，让你去跳，要做多就是找出坑，把它填平，确保自己不会掉下去。
2. 时间预算也是非常重要的考虑因素，如果时间预算不充裕的话，做这个难度还确实不小
3. 主动性也是一个十分重要的因素，卡到一个部分，查完后还一脸懵逼，就问一下，教练十分敬业的帮助你，旁敲侧击地地提醒你，都会帮你把作业给往下推进。但是，前提是，你的主动性得强，关键在你自己。

#### day11

学习时长:20个小时

卡点

1. 安装文档解析库，折腾了一波
2. 用requests请求公众号文章连接，获取返回结果response,把微信公众号的正文提取出来
3. 开通邮箱这个权限后，输入的不是邮箱密码而是授权码，而且输入的位置是在终端
4. 最后是在自己的邮箱先测试，反复第想

感悟

1. 里面的步骤一步一步来，一步成功后，在继续下面的步骤，比如print出来，看这一步成功后再进行一步，避免问题堆积
2. 想起一首歌词，“这一路上走走停停，顺着少年漂流的痕迹”，因为事比较多，所以自学这个也是挺艰难的，这几天都是，做做停停，不过只要不放弃，就有机会，如果放弃了，那这件事肯定凉凉。
3. 辅导员和教练，助教的存在真的很重要，虽然培养的是自学能力，但是如果只靠自己而不去向前辈请教，我自己肯定做不到并且极其容易放弃，我想很多人肯定也做不到，所以有什么困惑，多和他们交流交流，收获绝对是很大的

#### day12

学习时长:5.5个小时

卡点

1. 安装wxpy,显示需要升级pip，根据提示输入指令后，又出现安装环境错误，直接把错误复制，在百度中搜索后，根据简书上的提示，进行改写，又出现错误。然后发现，在升级pip 的时候的命令少写一个数字，填上后，错误消失，在cmd 中查看晒否安装wxpy成功，成功后继续下一步
2. 在终端测试得回来的数据不显示   自动接受的文章，把参考资料的延申都大致看完后，参考实例代码，运行琢磨，发现需要，把最后的embed（）函数也剪切过来，才能检验前几段程序，可是还是没解决问题，又在网上转一圈后，在何教练的点播下，又改了一行代码，解决
3. 文本出现了，但是，词频没出现，经过琢磨后， 发现把stats_word11名字，改一下，解决

感悟

1. 在卡点三花费时间最长，最后教练一句话解决，教练的重要性，不言自明
2. 作业是作业，但是相关的衍生工作，都够自己的琢磨一整子的，就比如今天的wxpy: 用 Python 玩微信
3. 也刚好在室友的帮助下，调试很多遍成功，相关实用性的训练有时需要求助的不止一个人
4. 经过这段时间的思考，认为，自学的常态是，碰到问题，明确问题，想办法解决问题。其中最为关键的是想办法解决问题，相关论坛的，内网和外网，教练们，等等，想各种渠道去解决问题。

#### day13

学习时长:3.5个小时

卡点

1. 参考matplotlib的资料，将day12中的结果生成一张图片，将演示代码直接复制能出现一样的图片结果>现在想办法在这个代码改改，把day12的结果想办法引进来
2. 将返回给好友的内容以表的形式出现，参考作业代码不行，通过百度，直接把上面的结果转化成list形式，可以返回给好友

感悟

1. day13新增的部分更像是一个工具，一个将表格转换成图片的工具，将里面的东西稍微变变型就能弄出自己的东西

#### day14 

学习时长:6个小时

感悟

1. 这一路走过来，像极了过关的游戏的感觉，你会遇到各种各样的卡点，不要怕，那是进步过关的入口
2. 最后还是要感谢教练、辅导员、助教的帮助和鼓励，才让我有能力、有信心、有勇气去与困难做斗争，去把时间当朋友，披荆斩浪，勇往直前。

**Comment by realcaiying** [comment]
已收录。

https://github.com/selfteaching-learning-notes/selfteaching-learning-notes.github.io/commit/d27622a9a5478422d46c66b52b804579b65bcaae
