### ISSUE TITLE
1901050136-自学训练营自学7群-自学是门手艺 part1.E.1

### ISSUE THREAD

**Issue by ShihaoCui** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#77]
### 学员信息
- 学号：<1901050136>
- 学习内容：<自学是门手艺 part1.C. and D. >
- 学习用时：<60mins>
### 学习笔记

<收获总结>
# recap 

This part is to introduce some basic concepts for programming and python language.

The story of George Boole is used as the entrance of the programming language. He is a good example for self-studying and his book is needed to read in the future.

The one invention of Boole is the boolean operands and this can be applied to control the flow of programs. It tells the program when to go to a specific case and when to stop. In python, `if-else` is used to do this.

The program is aimed to implement a thing. For a specific program, its efficiency can be improved further. This is the research of algorithm optimization. This is a high-level thing since it needs wisdom and thoughts and is not a just thing of the tool.

The function is used to encapsulate a certain program and make it can be applied in other places, i.e. calling or invoking functions. 
<遇到的难点与问题（是否解决）>

**Comment by XINGRUFANG** [comment]
link #78
