### ISSUE TITLE
1901050017-自学训练营学习4群-PYTHON 14天 入门

### ISSUE THREAD

**Issue by kagamiqyah** [selfteaching-learning-notes/selfteaching-learning-notes.github.io#9]
### 学员信息
- 学号：1901050017   王晓镜
- 学习内容：14天python入门营
- 学习用时：40小时

### 学习笔记
我选择的是预约制学习，可以自己学完一次作业以后马上申请学习后面的作业。

#### 训练营带给我的
1. 训练营的每日作业都会迫使我主动思考，逼迫我一字一句去阅读要求，不按照要求做就会完不成作业，强制改正了我阅读不仔细的问题。
2. 社群式学习。不是单打独斗地面对困难，‘恐惧未知’这条恶龙不会在大脑中盘旋很久，因为有教练和同学在帮助着我，即使偶尔会深陷泥沼，只要我呼喊，他们就会立刻施于援手。学习效率大大提高。
3. 养成了阅读官方档案的习惯。这一点非常重要，每天的作业都会给出官方档案的链接，在群里大家也会互相提醒，随时巩固这个好习惯。
4. 学会了程序员思考，遇到难点，学会把它分成一小段一小段来解决，并且用自己熟知的知识尝试类比来解释给自己听。
5. 深刻地认识到了借鉴优秀程序员的智慧结晶是非常重要的，有质量的输出的前提是要有质量地输入，如果能看懂优质代码，并为己用，这本身就是一种进步。

##### 千里之行，始于足下----训练营第一天 day1-day2作业完成

自学训练营最能反映学习中不好的习惯。

收到“自学任务清单”，开始学习。清单表达的很清楚，但真的就是我看不见它，它一直在那里。清单里要求先看参考资料，我愣是自动掠过这一步，现在想来，真的是很佩服我的大脑，就这样习惯性地怕麻烦，找捷径，试图略过一切，然后还妄想能快速完成作业。

我在卡壳以后，冷静了下来，重新从清单1开始看，耐心地看了参考资料，认真地对待每一句话，这样竟然神奇地解决了每一个问题。
这次我认识到想要解决问题，还是得克服自己的毛病。在做作业时，踏踏实实。

因为习惯不好，没有阅读官方文件。在一个小到不能再小的步骤上卡壳了1个小时。

在查看社群其他人的聊天中，找到了解决方案，在第一天截止时间前完成了第一天的打卡。

好久没体会过沉浸的感觉了，就是那种猛一抬头，一个小时过去了。

第一天的学习让我认识到想要解决问题，还是得克服自己的毛病。在做作业时，要踏踏实实。

##### 纸上得来终觉浅，绝知此事须躬行----训练营第二天 day3-day5作业完成

看到群里的同学都在陆续地交作业（社群学习的好处，时刻督促自己），我停掉了“自我攻击的剧情”，心里开始接受一件事，那就是遇到不会的问题时是正常的，不久的将来一定会熟练掌握的。于是，心理突破了，脑子和手并用，完成作业的速度就提上来了。再加上，我不再以借鉴代码为耻，目的就是为了学习，我再借鉴的基础上再加上自己的理解，现在已经能够写出代码的一大部分了。
自主学习加同学间互助式学习，具像化了李笑来老师说的：
> 很多人有莫名其妙的误解，以为“自学”（self-learning)就一定是“自己独自学”（solo-learning)，殊不知，自学也需要社交。

> 别怕！ 啥也别怕！没什么可怕的！

*收获总结*：

+ 学会了抄代码。不再谴责自己没用，心安理得地抄了三种代码，然后运行，改写代码，最后改写出了自己的代码。
- 敢于调试，以前总是怕出现问题，手心冒汗，后背冒汗，脑袋发麻，如今出现问题我就搜索问题是什么意思，然后冷静地去想办法解决。
+ 学会去github里的issues找问题答案。

##### 读书破万卷，下笔如有神----训练营第三天 day6作业完成

*收获总结*：

行之有效的方法就是大量阅读官方资料，因为是社群学习+github分布式交作业，所以可以看到很多同学的代码。学习+模仿，是我在3天时间内完成day1-6的任务的秘诀。输入有质量才是最好的进步方式。

##### 读书不觉已春深，一寸光阴一寸金----训练营第四天 day7-day10作业完成

写python代码，做有用之事。在第四天，完成到了训练营day10的任务。

*收获总结*：

+ 因为这几天的学习，让我深刻体会到了废寝忘食、孜孜不倦、目不转睛、聚精会神、茶饭不思的境界，心流时间可以达到3、4个小时不间断。
- 对阅读更是有了新的体会：一字不落的读，来回反复地读，不躲避，不放弃，迎着困难读。
+ 对官方文档更加看重，对google也更加依赖，李笑来老师说的好：

> 学习任何东西，首先看官方文档或产品说明书，那些学习高手都是会先阅读官方文档的人。

> 能google出答案的问题，就不需要去麻烦别人.google、stackoverflow、wikipedia、youtube这都是自学人经常要去搜索的好地方。

##### 千里之行，始于足下----训练营第五天 day11-day12作业完成

> 眼是懒汉，手是好汉
> 不怕，一点也不可怕，不难，一点也不难。

在这天，我清楚地感受到今天不想做作业地心情，抵触、逃避、恐慌、焦虑。。。。。。
因为预知了困难，提前看GitHub 上的issues里都是关于day11作业的困惑和疑问，心里多少有些抵触。但是我知道只有做了才能解决，而不是空想。逃避没有任何用，把任务分解，一句话一句话地去实施。

随着着手敲代码的开始，这一天没有想象中困难，最后完成了day11-12的任务。

*收获总结*：
+ 深刻理解了，写代码如同搭积木，一个函数如同一块乐高积木，只要一块一块加上去，就具像化了自己的目标。

- 一直听说python爬虫技术，今天终于得以实施，抓去了张小龙的演讲稿并做了处理，返回了邮件。
+ 一直听说微信机器人，今天又亲自实施，和微信好友互动有无，她给我文章，我给她文章的数据，是自动的哦。

- 这次我好像真的很可以确信，学python不会再半途而废了，也许日后如同excel一样，用的机会越来越多了。

##### 咬定青山不放松----训练营第六天 day13作业未完成

距离上一次提交作业已经过了两天，因为这次遇到了问题。求助issues和助教，还是未能解决。
matplot绘制图表在我的电脑中显示不出来。无解中。
##### 敏而好学，不耻下问----训练营第7天 day13-14作业完成
在google和其他同学的作业中寻找到答案，遇到两个大问题最终解决。
1、matplot绘制图表在我的电脑中显示不出来。刚开始我以为代码没写对，后来用官方文档里的作业依然显示不出来。我才想到可能是其他问题，因为不自信，所以才会在代码上改了又改，耽误了时间，而真正问题不能解决。
这是因为`matplotlib`的`backend`设置成了`agg`格式得在整个代码前加上
```
import matplotlib
matplotlib.use（’TkAgg’)
```
而且要注意要在import matplotlib.pyplot前使用。
2、微信返回数据乱码
a.去[fontplace](https://www.fontpalace.com/)下载`SimHei`字体，其他也可以。但网页打不开，我就选择了科学的方法，一次ok。
b.把这个ttf文件手动添加到`matplotlib`的`mpl_data`里的`tff`文件夹里，这里都是已装字体。
c.找到`matplotlibrc`文件，打开，这是不要害怕，直接找到`font.sans-serif`，在冒号后面打出：`SimHei`。关闭文件。
在代码里添加
```
from pylab import mpl
mpl.rcParams[‘font.sans-serif’] = [‘SimHei’]
```
事情到此，我的代码已经完全能显示了，并且中文也出来了。
而且最重要的是通过此次的问题解决，让我对这次的作业代码非常熟悉，已经能变换地写出好几种相同功能的代码了。也算是有所收获。

最终的一天来到了，全部学完了训练营的任务，中间有困惑，有惊喜，最终收获的是满满的知识和弥足珍贵的自学体验，升级了自学的操作系统，对未来编程技能的使用充满了信心。

**Comment by realcaiying** [comment]
已收录 

https://github.com/selfteaching-learning-notes/selfteaching-learning-notes.github.io/commit/e10bde67608db36f2f76edaf2029305d0c261666
